Add ~/local to list of global library install locations
ecmwf/findlibs pull request #9
Opened 2023-06-19 12:59 UTC by TomHodson

On my Mac machine, if I follow the[ odc build instructions](https://github.com/ecmwf/odc/blob/master/README.md#:~:text=git%20clone%20https,bin/odc%20%2D%2Dversion) and run `make install` I find that `libodccore.dylib ` ends up  in `~/local/lib/libodccore.dylib` and `find("odccore", pkg_name="odc")` cannot find it.

Hence I suggest adding `os.path.expanduser("~/local")` to the list of search directories for globally installed files which would fix this with no user intervention. 

I had previously set an `odc_DIR` environment variable to get this to work but then realised it doesn't propagate nicely to jupyter, and hence I can't `import codc` there. 

The alternative fix might be to add a way for `make install` to install to "$CONDA_PREFIX/lib/libodccore.dylib" since that is the first place`find` looks and seems like a reasonable place for ODCs`make install` command to put its libraries.

2023-06-19 12:59 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/findlibs?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/findlibs?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/findlibs?pullRequest=9) it.</sub>

2023-06-23 16:21 UTC, tlmquintino commented
I think we need a more generic solution. We only use ~/local as a placeholder in the examples of how to build our software. It is not meant to be an endorsement of a location to install software. For example, ECMWF installs software to /opt/ecmwf in our RPMs and DEBs binary packages.

How about we add the capability of reading a simple config file eg. ~/.findlibs.yaml
where users can define additional libraries paths?
or even define where particular libraries can be found (specific paths).

2023-06-23 16:23 UTC, tlmquintino commented
BTW, I dont mean that the idea of adding ~/local should be abandoned. I just mean that this should tigger a more in depth  solution.

2023-06-26 13:25 UTC, TomHodson commented
From reading the code of findlibs I understood that findlibs was essentually written to look for libraries in every conceivable place. In that context I think the default install path when you `make install` ODC should be findable by findlibs without furher user intervention.

With regards to the  `~/.findlibs.yaml` proposal, would the idea be to create a default file on `pip install findlibs` that contains sane defaults including `~/local` and `/opt/ecmwf`? Is it really necessary to have yet another tool specific dotfile?

Regarding the point about DEBsand RPM packages, I always assumed it was the job of the package manager to ensure that either they installed to findable locations or that they added their custom install location to, for example, LD_LIBRARY_PATH.

2023-06-26 13:33 UTC, tlmquintino commented
`~/local` is not an intended default. odc installation instructions are an _example_ not a recipe.
The default of building and installing odc is /usr/local which is already covered.

The aim of findlibs is not to find libraries in _every conceivable place_. It is to find libraries in the systems default locations + some other locations non-standard but often used locations, in a platform independent manner.

Package manager responsibilities are to install to system locations by default. This means typically _not_ relying on LD_LIBRARY_PATH, but on paths that the system linker uses by default like `/usr/local/' 

`~/.findlibs.yaml` should not be installed by findlibs. This is something that the user can provide and it is not an error if it is not there.

2023-06-26 13:40 UTC, tlmquintino requested changes
According to https://www.freedesktop.org/software/systemd/man/file-hierarchy.html this should be:
"~/.local/lib" not "~/local"

Please change local directory to be hidden.

2023-06-26 13:42 UTC, tlmquintino commented
I would like to see this PR to also add the `~/.findlibs.yaml` since it is strongly related to the issue at hand and a more user friendly solution.

2023-06-27 12:48 UTC, TomHodson commented
I'm done an initial implementation of findlibs.yml in https://github.com/ecmwf/findlibs/pull/10

2023-12-11 14:57 UTC, closed without merging